<a href="https://colab.research.google.com/github/Waliya451/Fraud-Detection/blob/main/Fraud_Detection_Logistic%26KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

Twitter human or bot dataset

In [22]:
dataset = pd.read_csv("./twitter_human_bots_dataset.csv")
dataset.drop(dataset.columns[0], axis=1, inplace=True)
dataset.drop('created_at', axis=1, inplace=True)
dataset.drop('description', axis=1, inplace=True)
dataset.drop('lang',axis=1, inplace=True)
dataset.drop('profile_background_image_url',axis=1, inplace=True)
dataset.drop('id', axis=1, inplace=True)
dataset.drop('screen_name', axis=1, inplace=True)

In [23]:
df = pd.DataFrame(dataset)
df

default_profile  default_profile_image  favourites_count  \
0                False                  False                 4   
1                False                  False               536   
2                False                  False              3307   
3                 True                  False              8433   
4                False                  False                88   
...                ...                    ...               ...   
37433             True                  False               651   
37434            False                  False              8839   
37435             True                  False               399   
37436            False                  False               967   
37437            False                  False              1092   

       followers_count  friends_count  geo_enabled                 location  \
0                 1589              4        False                  unknown   
1                  860            880        False           Estados Unidos   
2                  172            594         True          Los Angeles, CA   
3                  517            633         True           Birmingham, AL   
4               753678            116         True  England, United Kingdom   
...                ...            ...          ...                      ...   
37433              139           1105        False       Kingston Upon Hull   
37434          1121486            605         True                  unknown   
37435            85630            190        False  En constante movimiento   
37436              138            166         True          Los Angeles, CA   
37437                5             39        False                       中国   

                                       profile_image_url  statuses_count  \
0      http://pbs.twimg.com/profile_images/7874121826...           11041   
1      http://pbs.twimg.com/profile_images/8023296328...             252   
2      http://pbs.twimg.com/profile_images/1278890453...            1001   
3      http://pbs.twimg.com/profile_images/1284884924...            1324   
4      http://pbs.twimg.com/profile_images/9952566258...            4202   
...                                                  ...             ...   
37433  http://pbs.twimg.com/profile_images/5844684414...             340   
37434  http://pbs.twimg.com/profile_images/9511349456...           24970   
37435  http://pbs.twimg.com/profile_images/1174733822...            6174   
37436  http://pbs.twimg.com/profile_images/1265807908...             982   
37437  http://pbs.twimg.com/profile_images/1688940752...            1563   

       verified  average_tweets_per_day  account_age_days account_type  
0         False                   7.870              1403          bot  
1         False                   0.183              1379        human  
2         False                   0.864              1159        human  
3         False                   0.889              1489        human  
4          True                   1.339              3138        human  
...         ...                     ...               ...          ...  
37433     False                   0.084              4028        human  
37434      True                   8.976              2782        human  
37435      True                   2.226              2773        human  
37436     False                   0.339              2899        human  
37437     False                   0.493              3172          bot  

[37438 rows x 13 columns]

In [24]:
pd.set_option('future.no_silent_downcasting', True)
result = df['account_type'].replace({'human': 0, 'bot': 1})
df['account_type'] = result.infer_objects(copy=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37438 entries, 0 to 37437
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   default_profile         37438 non-null  bool   
 1   default_profile_image   37438 non-null  bool   
 2   favourites_count        37438 non-null  int64  
 3   followers_count         37438 non-null  int64  
 4   friends_count           37438 non-null  int64  
 5   geo_enabled             37438 non-null  bool   
 6   location                37434 non-null  object 
 7   profile_image_url       37437 non-null  object 
 8   statuses_count          37438 non-null  int64  
 9   verified                37438 non-null  bool   
 10  average_tweets_per_day  37438 non-null  float64
 11  account_age_days        37438 non-null  int64  
 12  account_type            37438 non-null  int64  
dtypes: bool(4), float64(1), int64(6), object(2)
memory usage: 2.7+ MB


In [25]:
feats = df.drop('account_type', axis=1)
feats = feats.drop('profile_image_url', axis=1)
feats = feats.drop('location', axis=1).to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(feats, df['account_type'].to_numpy(), test_size=0.2, random_state=42)

Training the model using Logistic Regression

In [26]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train, Y_train)

c:\Users\PMLS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Accuracy

In [27]:
# accuracy on training data
X_train_prediction1 = logistic_model.predict(X_train)
training_data_accuracy1 = accuracy_score(X_train_prediction1, Y_train)
print('Accuracy on Training data : ', training_data_accuracy1)
# accuracy on test data
X_test_prediction1 = logistic_model.predict(X_test)
test_data_accuracy1 = accuracy_score(X_test_prediction1, Y_test)
print('Accuracy score on Test Data : ', test_data_accuracy1)

Accuracy on Training data :  0.7585308848080133
Accuracy score on Test Data :  0.7638888888888888


In [28]:
print(confusion_matrix(Y_test, X_test_prediction1))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, X_test_prediction1,target_names=target_names))

[[4350  651]
 [1117 1370]]
              precision    recall  f1-score   support

     class 0       0.80      0.87      0.83      5001
     class 1       0.68      0.55      0.61      2487

    accuracy                           0.76      7488
   macro avg       0.74      0.71      0.72      7488
weighted avg       0.76      0.76      0.76      7488



**KNN Classifier**

In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [30]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, Y_train)

KNeighborsClassifier()

In [31]:
X_train_prediction2 = knn_model.predict(X_train)
training_data_accuracy2 = accuracy_score(X_train_prediction2, Y_train)

In [32]:
X_test_prediction2 = knn_model.predict(X_test)
test_data_accuracy2 = accuracy_score(X_test_prediction2, Y_test)

In [33]:
print('Accuracy score on Training Data : ', training_data_accuracy2)
print('Accuracy score on Test Data : ', test_data_accuracy2)

Accuracy score on Training Data :  0.8925542570951586
Accuracy score on Test Data :  0.8505608974358975


In [34]:
print(confusion_matrix(Y_test, X_test_prediction2))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, X_test_prediction2,target_names=target_names))

[[4531  470]
 [ 649 1838]]
              precision    recall  f1-score   support

     class 0       0.87      0.91      0.89      5001
     class 1       0.80      0.74      0.77      2487

    accuracy                           0.85      7488
   macro avg       0.84      0.82      0.83      7488
weighted avg       0.85      0.85      0.85      7488



Decision Trees

In [36]:
from sklearn.tree import DecisionTreeClassifier
import pydotplus
from IPython.display import Image
from sklearn.tree import export_graphviz
from sklearn import tree

In [37]:
decisiontree = DecisionTreeClassifier(criterion='entropy',random_state=0)
dt_model = decisiontree.fit(X_train, Y_train)

In [44]:
dataset.drop(["profile_image_url"],axis=1,inplace=True)
dataset.drop(["location"],axis=1,inplace=True)

In [45]:
# Assuming 'decisiontree' is already trained
features = dataset.drop(["account_type"], axis=1)
target = dataset["account_type"]

# Check consistency
print(f"Number of features used in the model: {len(features.columns)}")
print(f"Number of unique target values: {len(target.unique())}")

# Create DOT data
dot_data = tree.export_graphviz(
    decisiontree,
    out_file=None,
    feature_names=features.columns,
    class_names=target.unique().astype(str),
    filled=True,
    rounded=True,
    special_characters=True
)

# Draw graph
graph = pydotplus.graph_from_dot_data(dot_data)
# Show graph
Image(graph.create_png())
graph.write_pdf("tree.pdf")


Number of features used in the model: 10
Number of unique target values: 2
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.192154 to fit



True

In [ ]:
print("Features used in the model:", features.columns)
print("Unique target values:", target.unique())


Features used in the model: Index(['default_profile', 'default_profile_image', 'favourites_count',
       'followers_count', 'friends_count', 'geo_enabled', 'location',
       'profile_image_url', 'statuses_count', 'verified',
       'average_tweets_per_day', 'account_age_days'],
      dtype='object')
Unique target values: ['bot' 'human']


In [ ]:
X_train_prediction3 = dt_model.predict(X_train)
training_data_accuracy3 = accuracy_score(X_train_prediction3, Y_train)

In [ ]:
X_test_prediction3 = dt_model.predict(X_test)
test_data_accuracy3 = accuracy_score(X_test_prediction3, Y_test)

In [ ]:
print('Accuracy score on Training Data : ', training_data_accuracy3)
print('Accuracy score on Test Data : ', test_data_accuracy3)

Accuracy score on Training Data :  1.0
Accuracy score on Test Data :  0.8267895299145299


In [ ]:
print(confusion_matrix(Y_test, X_test_prediction3))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, X_test_prediction3,target_names=target_names))

[[4321  680]
 [ 617 1870]]
              precision    recall  f1-score   support

     class 0       0.88      0.86      0.87      5001
     class 1       0.73      0.75      0.74      2487

    accuracy                           0.83      7488
   macro avg       0.80      0.81      0.81      7488
weighted avg       0.83      0.83      0.83      7488

